### ISSUE TITLE
TypeScript definitions support

### ISSUE THREAD

**Issue by leocaseiro** [vpegado/angular-markdown-filter#10]
Hi, do you have any plans of supporting a TypeScript definitions file, or does one exist that is not registered on [typings](https://github.com/typed-typings) or not on [DefinitelyTyped](http://definitelytyped.org/)?

Thanks

**Comment by vpegado** [comment]
@leocaseiro
No existing definition that I'm aware of.
No plans of adding any up to this point.
The module is fairly small so adding definitions shouldn't be a big effort. I might look in to it myself but you're welcome to do a pull request if you don't want to wait.
