### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by LulzAugusto** [vpegado/angular-markdown-filter#8]
Could you please publish it to NPM? It would help those using Browserify + NPM to handle dependencies (like we do at Tago).

By the way, thanks for spending the time doing this filter. :)

**Comment by vpegado** [comment]
Published at https://www.npmjs.com/package/angular-markdown-filter
so now you can:
```
$ npm install angular-markdown-filter
```

**Comment by LulzAugusto** [comment]
Thanks @vpegado
